dist: trusty

language: node_js
node_js:
 - "stable"
script: cd node; npm install nyc; npm test; cd ../angular; npm install @angular/cli; ng test;
services:
 - mongodb
 
addons:
 apt:
  sources:
   - google-chrome
  packages:
   - google-chrome-stable

cache:
 directories:
  - ./node_modules
